[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://store-production-385d.up.railway.app/api"

[[plugins]]
  package = "@netlify/plugin-nextjs"
