[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://store-api.matthewraynor.com/api"
  INTERNAL_API_URL = "https://store-api.matthewraynor.com/api"

[[plugins]]
  package = "@netlify/plugin-nextjs"
